In [31]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [32]:
df=pd.read_excel(r"C:\Users\91636\OneDrive\Desktop\Data-Analytics-Portfolio\Python\ML_practice\Dataset.xlsx")

In [33]:
print(df.columns)

Index(['Student_ID', 'Department', 'Attendance', 'Study_Hours',
       'Assignment_Score', 'Internal_Marks', 'Previous_GPA', 'Backlogs',
       'Library_Hours', 'Final_Score', 'Pass_Fail'],
      dtype='str')

In [34]:
X = df[
    [
        "Attendance",
        "Study_Hours",
        "Assignment_Score",
        "Internal_Marks",
        "Previous_GPA",
        "Backlogs",
        "Library_Hours",
        "Final_Score"

    ]
]

y = df["Pass_Fail"]

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [36]:
X_train

,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Final_Score
2,61,3.5,55,52,6.4,3,1,54
0,92,8.0,88,82,8.6,0,6,87
3,95,9.0,94,91,9.1,0,8,93

In [37]:
X_test

,Attendance,Study_Hours,Assignment_Score,Internal_Marks,Previous_GPA,Backlogs,Library_Hours,Final_Score
1,76,5.0,72,68,7.2,1,3,71
4,68,4.0,61,58,6.8,2,2,60

In [38]:
y_train

2    Fail
0    Pass
3    Pass
Name: Pass_Fail, dtype: str

In [39]:
y_test

1    Pass
4    Pass
Name: Pass_Fail, dtype: str